#!/usr/bin/env node
/**
 * Generates Vue docs pages from .stories.js files.
 *
 * Usage:
 *   node scripts/build-docs.js               # all stories
 *   node scripts/build-docs.js DataTable FormBuilder   # specific components
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

// ── Helpers ───────────────────────────────────────────────────────────────────

function toKebab(name) {
  return name.replace(/([A-Z])/g, (m, _, offset) =>
    offset === 0 ? m.toLowerCase() : '-' + m.toLowerCase()
  )
}

function toTitle(name) {
  return name.replace(/([A-Z])/g, (m, _, offset) => (offset === 0 ? m : ' ' + m))
}

function categoryDisplay(cat) {
  return cat.replace(/([A-Z])/g, (m, _, offset) => (offset === 0 ? m : ' ' + m))
}

// ── File discovery ─────────────────────────────────────────────────────────────

function walkForStories(dir, results = []) {
  if (!fs.existsSync(dir)) return results
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walkForStories(full, results)
    else if (entry.name.endsWith('.stories.js')) results.push(full)
  }
  return results
}

function findStoryFiles(filter = []) {
  const all = walkForStories(path.join(ROOT, 'packages'))
  if (!filter.length) return all
  return all.filter((f) => {
    const base = path.basename(f, '.stories.js')
    const name = base.startsWith('Oc') ? base.slice(2) : base
    return filter.includes(name)
  })
}

// ── Stories file parsing ───────────────────────────────────────────────────────

// Find matching closing brace for an opening brace at startPos
function findClosingBrace(str, startPos) {
  let depth = 0
  for (let i = startPos; i < str.length; i++) {
    if (str[i] === '{') depth++
    else if (str[i] === '}') {
      depth--
      if (depth === 0) return i
    }
  }
  return -1
}

// Extract named exports that have a render function (skip Playground)
function extractStoryNames(content) {
  const names = []
  const re = /^export\s+const\s+(\w+)\s*=\s*\{/gm
  let m
  while ((m = re.exec(content)) !== null) {
    const name = m[1]
    if (name === 'Playground') continue
    const bracePos = content.indexOf('{', m.index + m[0].length - 1)
    const end = findClosingBrace(content, bracePos)
    if (end === -1) continue
    const block = content.slice(bracePos, end + 1)
    // only include stories with a render function
    if (!/\brender\s*:/.test(block)) continue
    names.push(name)
  }
  return names
}

// ── Path helpers ───────────────────────────────────────────────────────────────

function getComponentName(filePath) {
  const base = path.basename(filePath, '.stories.js')
  return base.startsWith('Oc') ? base.slice(2) : base
}

function getCategory(filePath) {
  const rel = path.relative(ROOT, filePath)
  const parts = rel.split(path.sep)
  // packages / core|dashboard / src / CATEGORY / ...
  return parts[3] ?? 'Other'
}

function getPackage(filePath) {
  return filePath.includes(`${path.sep}dashboard${path.sep}`)
    ? '@orchidui/dashboard'
    : '@orchidui/core'
}

// Relative import path from src/docs/pages/ to the story file
function relativeImport(storyFilePath) {
  return path
    .relative(path.join(ROOT, 'src', 'docs', 'pages'), storyFilePath)
    .split(path.sep)
    .join('/')
}

// ── Page generation ───────────────────────────────────────────────────────────

function generatePage(storyFilePath, componentName, storyNames) {
  const relPath = relativeImport(storyFilePath)
  const pkg = getPackage(storyFilePath)

  const examplesCode = storyNames
    .map((name) => {
      const id = toKebab(name)
      const title = toTitle(name)
      return `  {
    id: '${id}',
    title: '${title}',
    description: ${name}.description,
    highlights: ${name}.highlights,
    code: ${name}.code,
    preview: ${name}.render ? defineComponent(${name}.render()) : null,
  },`
    })
    .join('\n')

  return `<script setup>
import { defineComponent } from 'vue'
import storyDefault, { ${storyNames.join(', ')} } from '${relPath}'
import ComponentPage from '../../docs-components/ComponentPage.vue'

const meta = {
  title: '${componentName}',
  description: storyDefault.parameters?.docs?.description?.component ?? '',
  package: '${pkg}',
}

const examples = [
${examplesCode}
]
</script>

<template>
  <ComponentPage :meta="meta" :examples="examples" />
</template>
`
}

// ── Router generation ──────────────────────────────────────────────────────────

function generateRouter(components) {
  const childRoutes = components
    .map(
      (c) =>
        `      { path: 'components/${toKebab(c.name)}', component: () => import('./docs/pages/${c.name}.vue') },`
    )
    .join('\n')

  return `// Generated by scripts/build-docs.js — do not edit manually
export default [
  { path: '/', component: () => import('./AppLayout.vue') },
  {
    path: '/docs',
    component: () => import('./layouts/DocsLayout.vue'),
    children: [
      { path: '', component: () => import('./docs-components/DocsHome.vue') },
${childRoutes}
    ]
  }
]
`
}

// ── Sidebar config generation ──────────────────────────────────────────────────

function generateSidebarConfig(components) {
  const grouped = {}
  for (const c of components) {
    if (!grouped[c.category]) grouped[c.category] = []
    grouped[c.category].push({ name: c.name, route: `/docs/components/${toKebab(c.name)}` })
  }

  const sorted = Object.entries(grouped)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([cat, items]) => ({
      category: categoryDisplay(cat),
      items: items.sort((a, b) => a.name.localeCompare(b.name))
    }))

  return `// Generated by scripts/build-docs.js — do not edit manually
export default ${JSON.stringify(sorted, null, 2)}
`
}

// ── Main ───────────────────────────────────────────────────────────────────────

const filter = process.argv.slice(2)
const storyFiles = findStoryFiles(filter)

if (!storyFiles.length) {
  console.error('No story files found.')
  process.exit(1)
}

fs.mkdirSync(path.join(ROOT, 'src', 'docs', 'pages'), { recursive: true })

const components = []

for (const filePath of storyFiles) {
  const content = fs.readFileSync(filePath, 'utf-8')
  const storyNames = extractStoryNames(content)

  if (!storyNames.length) {
    console.log(`  skip  ${path.basename(filePath)} — no renderable stories`)
    continue
  }

  const name = getComponentName(filePath)
  const category = getCategory(filePath)
  const pageContent = generatePage(filePath, name, storyNames)
  const outPath = path.join(ROOT, 'src', 'docs', 'pages', `${name}.vue`)

  fs.writeFileSync(outPath, pageContent)
  console.log(`  ✓  ${name}.vue  (${storyNames.length} examples: ${storyNames.join(', ')})`)

  components.push({ name, category, route: `/docs/components/${toKebab(name)}` })
}

// Always regenerate sidebar + router based on ALL currently generated pages
// (so running with a filter doesn't wipe the rest)
const existingPages = fs
  .readdirSync(path.join(ROOT, 'src', 'docs', 'pages'))
  .filter((f) => f.endsWith('.vue'))
  .map((f) => f.replace('.vue', ''))

const allComponents = [...new Set([...components.map((c) => c.name), ...existingPages])].map(
  (name) => {
    const existing = components.find((c) => c.name === name)
    if (existing) return existing
    // For pages already on disk but not re-generated this run, infer category from stories path
    const storyFile = findStoryFiles([name])[0]
    const category = storyFile ? getCategory(storyFile) : 'Other'
    return { name, category, route: `/docs/components/${toKebab(name)}` }
  }
)

fs.writeFileSync(
  path.join(ROOT, 'src', 'docs', 'sidebar-config.js'),
  generateSidebarConfig(allComponents)
)
console.log(`  ✓  sidebar-config.js  (${allComponents.length} components)`)

fs.writeFileSync(path.join(ROOT, 'src', 'router.js'), generateRouter(allComponents))
console.log(`  ✓  router.js`)

console.log(`\nDone! Run "npm run dev:landing" and visit /docs`)
