// Generated by scripts/generate-docs.js — do not edit manually
export default [
  { path: '/', component: () => import('./AppLayout.vue') },
  {
    path: '/docs',
    component: () => import('./layouts/DocsLayout.vue'),
    children: [
      { path: '', component: () => import('./docs/DocsHome.vue') },
      { path: 'components/data-table', component: () => import('./docs/pages/DataTable.vue') },
      { path: 'components/form-builder', component: () => import('./docs/pages/FormBuilder.vue') },
    ]
  }
]
