name: Publish

on:
  push:
    branches:
      - development
      - sandbox

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Running CI
        run: npm ci

      - name: Build Orchid Core
        run: npm run publish-dev:core

      - name: Publish Orchid Dashboard
        run: npm run publish-dev:dashboard
