---
on:
  push:
    branches: development
jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Running ci
        run: npm ci
      - name: Login npm
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm install
      - name: build orchid core
        run: npm run publish-dev:core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish orchid dashboard
        run: npm run publish-dev:dashboard
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
