---
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Running ci
        run: bun install
      - name: Login npm
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: build orchid core
        run: bun run publish:core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish orchid dashboard
        run: bun run publish:dashboard
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
