name: Publish Latest

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-latest:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 22.14.0
          registry-url: https://registry.npmjs.org

      - name: Update npm
        run: npm install --global npm@11.5.1

      - name: Verify Node and npm
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Publish core
        run: npm run publish:core

      - name: Publish dashboard
        run: npm run publish:dashboard
