name: Publish Latest

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-latest:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish core
        run: npm run publish:core

      - name: Publish dashboard
        run: npm run publish:dashboard
